/* This file was generated by typetether */
/* tslint:disable */

import Ajv from 'ajv';
import createPostUnwrapped from './actions/createPost.action';
import getUsersUnwrapped from './actions/getUsers.action';

const ajv = new Ajv();
type GetOptions <F> = F extends (options: infer G, ...rest: any[]) => any ? G : undefined;
type GetRest<F> = F extends (options: any, ...rest: infer G) => any ? G : undefined;
type GenericAction<R> = (...args: any[]) => R;

const createPostOptionsSchema = {"$schema":"http://json-schema.org/draft-07/schema#","anyOf":[{"additionalProperties":false,"defaultProperties":[],"properties":{"content":{"type":["null","string"]},"title":{"type":"string"}},"required":["title"],"type":"object"},{"additionalProperties":false,"defaultProperties":[],"properties":{"foo":{"type":["string","number"]},"posts":{"$ref":"#/definitions/default"}},"required":["foo","posts"],"type":"object"}],"definitions":{"default":{"additionalProperties":false,"defaultProperties":[],"properties":{"content":{"type":"string"},"id":{"type":"number"},"title":{"type":"string"}},"required":["content","id","title"],"type":"object"}}};
const createPostValidateOptions = ajv.compile({ ...createPostOptionsSchema, $async: true });

const createPostResultSchema = {"$schema":"http://json-schema.org/draft-07/schema#","additionalProperties":false,"defaultProperties":[],"properties":{"content":{"type":"string"},"id":{"type":"number"},"title":{"type":"string"}},"required":["content","id","title"],"type":"object"};
const createPostValidateResult = ajv.compile({ ...createPostResultSchema, $async: true });
createPost.hasOptions = true;
createPost.hasResult = true;
export async function createPost(rawOptions: unknown, ...rest: GetRest<typeof createPostUnwrapped>): ReturnType<typeof createPostUnwrapped> {
  const actionFn: GenericAction<ReturnType<typeof createPostUnwrapped>> = createPostUnwrapped;
  const options: GetOptions<typeof createPostUnwrapped> = await createPostValidateOptions(rawOptions);
  const rawResult = await actionFn(options, ...rest);
  return await createPostValidateResult(rawResult);
}

const getUsersResultSchema = {"$schema":"http://json-schema.org/draft-07/schema#","items":{"additionalProperties":false,"defaultProperties":[],"properties":{"id":{"type":"number"},"name":{"type":"string"}},"required":["id","name"],"type":"object"},"type":"array"};
const getUsersValidateResult = ajv.compile({ ...getUsersResultSchema, $async: true });
getUsers.hasOptions = false;
getUsers.hasResult = true;
export async function getUsers(_: unknown, ...rest: Parameters<typeof getUsersUnwrapped>): ReturnType<typeof getUsersUnwrapped> {
  const actionFn: GenericAction<ReturnType<typeof getUsersUnwrapped>> = getUsersUnwrapped;
  const rawResult = await actionFn(...rest);
  return await getUsersValidateResult(rawResult);
}

export default {
  createPost,
  getUsers,
};
