/* tslint:disable */
/* DO NOT EDIT
   Generated by server/scripts/build-client-lib.js
*/

export interface Options {
  content?: null | string;
  title: string;
  [k: string]: any;
}

export interface Result {
  content: string;
  id: number;
  title: string;
  [k: string]: any;
}

export default function createPost(options: Options): Promise<Result>;
